package co.edu.udistrital.dulcesparamiamor.services.validaramor;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 5/1/2016 8:57:45 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class OEValidarAmor implements KvmSerializable {
    
    public String correo;
    public String imagenAmor;
    
    public OEValidarAmor(){}
    
    public OEValidarAmor(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("correo"))
        {
            Object obj = soapObject.getProperty("correo");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                correo = j.toString();
            }else if (obj!= null && obj instanceof String){
                correo = (String) obj;
            }
        }
        if (soapObject.hasProperty("imagenAmor"))
        {
            Object obj = soapObject.getProperty("imagenAmor");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                imagenAmor = j.toString();
            }else if (obj!= null && obj instanceof String){
                imagenAmor = (String) obj;
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return correo;
            case 1:
                return imagenAmor;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 2;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "correo";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "imagenAmor";
                break;
        }
    }

    @Override
    public void setProperty(int arg0, Object arg1) {
    }

    public String getCorreo() {
        return correo;
    }

    public void setCorreo(String correo) {
        this.correo = correo;
    }

    public String getImagenAmor() {
        return imagenAmor;
    }

    public void setImagenAmor(String imagenAmor) {
        this.imagenAmor = imagenAmor;
    }


}
