package co.edu.udistrital.dulcesparamiamor.services.validaramor;
//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 5/1/2016 8:57:45 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class OSValidarAmor implements KvmSerializable {
    
    public int codigoRespuesta;
    public String mensajeRespuesta;
    
    public OSValidarAmor(){}
    
    public OSValidarAmor(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("codigoRespuesta"))
        {
            Object obj = soapObject.getProperty("codigoRespuesta");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                codigoRespuesta = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                codigoRespuesta = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("mensajeRespuesta"))
        {
            Object obj = soapObject.getProperty("mensajeRespuesta");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                mensajeRespuesta = j.toString();
            }else if (obj!= null && obj instanceof String){
                mensajeRespuesta = (String) obj;
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return codigoRespuesta;
            case 1:
                return mensajeRespuesta;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 2;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "codigoRespuesta";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "mensajeRespuesta";
                break;
        }
    }

    public int getCodigoRespuesta() {
        return codigoRespuesta;
    }

    public String getMensajeRespuesta() {
        return mensajeRespuesta;
    }

    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
