package co.edu.udistrital.dulcesparamiamor.model.webservices.autenticarusuario;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 4/10/2016 7:42:35 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class OEAutenticar implements KvmSerializable {
    
    public String correo;
    public String clave;
    
    public OEAutenticar(){}



    public OEAutenticar(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("correo"))
        {
            Object obj = soapObject.getProperty("correo");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                correo = j.toString();
            }else if (obj!= null && obj instanceof String){
                correo = (String) obj;
            }
        }
        if (soapObject.hasProperty("clave"))
        {
            Object obj = soapObject.getProperty("clave");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                clave = j.toString();
            }else if (obj!= null && obj instanceof String){
                clave = (String) obj;
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return correo;
            case 1:
                return clave;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 2;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "correo";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "clave";
                break;
        }
    }
    

    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
